name: sylva
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

  #Stage Manager
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1

  #UI
  another_flushbar: ^1.12.32
  flutter_svg: ^2.2.4
  responsive_framework: ^1.5.1
  shimmer: ^3.0.0
  fl_chart: ^1.2.0
  palette_generator_master: ^1.1.0

  #Navigation
  go_router: ^17.2.0

  #Storage
  shared_preferences: ^2.5.5
  storage_space: ^1.2.0
  flutter_dotenv: ^6.0.0
  isar_community: 3.3.2
  isar_community_flutter_libs: 3.3.2

  #Utils
  intl_utils: ^2.8.10
  haptic_feedback: ^0.6.4+3
  injectable: ^2.7.1+4
  lottie: ^3.3.3
  path_provider: ^2.1.5
  photo_manager: ^3.9.0
  photo_manager_image_provider: ^2.1.0
  opencv_dart: ^2.2.1+4
  google_fonts: ^8.0.2
  equatable: ^2.0.8
  image_picker: ^1.1.2
  image: ^4.3.0
  image_pixels: ^4.0.2
  native_exif: ^0.7.0
  exif: ^3.3.0
  path: ^1.9.1
  purchases_flutter: ^10.0.1
  url_launcher: ^6.3.2
  share_plus: ^13.1.0
  home_widget: ^0.9.2
  permission_handler: ^12.0.3
  connectivity_plus: ^6.1.4
  camera: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.15.0
  injectable_generator: ^2.12.1

# flutter pub run flutter_launcher_icons
# flutter_launcher_icons:
#   image_path: "assets/icons/icon.png"

#   android: "launcher_icon"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   adaptive_icon_background: "#093842"
#   adaptive_icon_foreground: "assets/icons/icon.png"

#   ios: true
#   remove_alpha_channel_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
  generate: true


flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
